sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image dockerfile"
  - docker build -t hjcho93/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hjcho93/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success!!!"